### ISSUE TITLE
Feature request: Save last look

### ISSUE THREAD

**Issue by TidusWulf** [Lana-chan/webgbcam#12]
I'd love it if I could have a cookie in place so that I can save the last used setting. Specifically, I'd like to be able to default to the greyscale color pallette.

**Comment by Lana-chan** [comment]
thanks for the suggestion! should be implemented by 7087b1ecde529d33add9b87524f7df7e02b61034 now

**Comment by TidusWulf** [comment]
I think this feature isn't working for me lately. I can't get the color pallete to remember the last selection.

**Comment by Lana-chan** [comment]
webgbcam is using [localStorage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API) to store brightness, contrast, palette, sharpness and mode (1bpp/2bpp) settings (or, to be clear, everything under the "gear" screen). what browser/device are you using? can you test if localStorage works in other pages/apps?

EDIT: also, what version of webgbcam do you see? (look at the window title) you may need to force a cache refresh if you do not see version 4.3 (latest at the time of this comment)

**Comment by TidusWulf** [comment]
I'm using the latest stable Firefox mobile on Android 14 on a Pixel 7. I don't really have issues with other websites, but maybe I'm just not visiting websites that use localstorage? I am on v4.3 of webgbcam.

If there's a flag or setting for localstorage, I can check it but I don't know where to look. I also have ublock origin installed as a Firefox plug in.

**Comment by Lana-chan** [comment]
i'm not sure if there's a way to check. i looked for a tool online but the only one i could find tries to test the _storage_ capacity of your browser by filling it up (nominally it should only be about 5MB but still not ideal)

i have no idea why it's not working for you. can you check the console to see if there are any javascript errors? i'll look into implementing a localstorage test into webgbcam which warns you if it can't write/retrieve from it.

if localstorage won't work for your device, i'm not sure there's anything i can do. cookies are ostensibly not a thing for PWAs, which is why localstorage is used instead.

**Comment by ztc0611** [comment]
This is not working on my phone on iOS 17.3/.4 either, both in browser directly or saved as a PWA. It also blacks out and stops working after you try to save a photo until you refresh but that's a separate issue.

**Comment by Lana-chan** [comment]
unfortunately i don't own any apple devices to test on. i'll see if i can find someone to help me check that on safari

**Comment by ztc0611** [comment]
I can't get it to dump any JS logs for some reason using the safari remote debugger tool, but it appears to be some combo of it losing camera permissions and the view not being refreshed. I just found out if you flip the camera then flip it back the feed resumes on the safari version. On the web app version when you flip the camera it asks for permissions again, then it starts working. This might be related to the settings save or might be its own unique issue.

**Comment by Lana-chan** [comment]
i don't think that has anything to do with the settings save, safari camera permissions have given me trouble in the past. the setting save shouldn't be related to it

**Comment by TidusWulf** [comment]
It seems to have fixed itself for now... Does the stored information expire after a certain amount of time, perhaps? Like a day or a week?

Sorry for long reply. I didn't notice you had got back to me...

**Comment by Lana-chan** [comment]
> Does the stored information expire after a certain amount of time, perhaps? Like a day or a week?

that would be entirely up to your browser, if it's the case. i haven't noticed on mine, and i develop mainly for mobile firefox
